name: Trigger Website Docs Update
on:
  push:
    branches: [ master ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: |
          response=$(curl -X POST -w "%{http_code}" -s -o /dev/null ${{ secrets.WEBSITE_DEPLOY_URL }})
          if [ "$response" -eq 200 ]; then
            echo "Deployment triggered successfully"
            exit 0
          else
            echo "Failed to trigger deployment. Status code: $response"
            exit 1
          fi
